-- ============================================================
--  University DB — Seed Data (lookup + small domain tables)
--  Target : MariaDB 11.7+
--  Phase  : 3 / 5
--  Tables : semesters, rooms, scholarships, departments
--  Note   : faculty, students, courses, enrollments, grade_events
--           are generated by generate_data.py (Phase 4)
-- ============================================================

USE university;

-- ============================================================
--  semesters  (20 rows — Fall/Spring 2020–2024, Summer 2021–2023)
-- ============================================================
INSERT INTO semesters (term, academic_year, name, start_date, end_date, enroll_deadline, is_active) VALUES
('Fall',   2020, 'Fall 2020',   '2020-08-31', '2020-12-18', '2020-08-21', FALSE),
('Spring', 2021, 'Spring 2021', '2021-01-19', '2021-05-14', '2021-01-08', FALSE),
('Summer', 2021, 'Summer 2021', '2021-05-24', '2021-08-06', '2021-05-14', FALSE),
('Fall',   2021, 'Fall 2021',   '2021-08-30', '2021-12-17', '2021-08-20', FALSE),
('Spring', 2022, 'Spring 2022', '2022-01-18', '2022-05-13', '2022-01-07', FALSE),
('Summer', 2022, 'Summer 2022', '2022-05-23', '2022-08-05', '2022-05-13', FALSE),
('Fall',   2022, 'Fall 2022',   '2022-08-29', '2022-12-16', '2022-08-19', FALSE),
('Spring', 2023, 'Spring 2023', '2023-01-17', '2023-05-12', '2023-01-06', FALSE),
('Summer', 2023, 'Summer 2023', '2023-05-22', '2023-08-04', '2023-05-12', FALSE),
('Fall',   2023, 'Fall 2023',   '2023-08-28', '2023-12-15', '2023-08-18', FALSE),
('Spring', 2024, 'Spring 2024', '2024-01-16', '2024-05-10', '2024-01-05', FALSE),
('Summer', 2024, 'Summer 2024', '2024-05-20', '2024-08-02', '2024-05-10', FALSE),
('Fall',   2024, 'Fall 2024',   '2024-08-26', '2024-12-13', '2024-08-16', FALSE),
('Spring', 2025, 'Spring 2025', '2025-01-21', '2025-05-16', '2025-01-10', FALSE),
('Summer', 2025, 'Summer 2025', '2025-05-27', '2025-08-08', '2025-05-16', FALSE),
('Fall',   2025, 'Fall 2025',   '2025-08-25', '2025-12-12', '2025-08-15', FALSE),
('Spring', 2026, 'Spring 2026', '2026-01-20', '2026-05-15', '2026-01-09', FALSE),
('Summer', 2026, 'Summer 2026', '2026-05-26', '2026-08-07', '2026-05-15', FALSE),
('Fall',   2026, 'Fall 2026',   '2026-08-31', '2026-12-18', '2026-08-21', FALSE),
('Spring', 2027, 'Spring 2027', '2027-01-19', '2027-05-14', '2027-01-08', FALSE);

-- Mark current semester active
UPDATE semesters SET is_active = TRUE WHERE name = 'Summer 2026';


-- ============================================================
--  rooms  (72 rows across 6 buildings)
-- ============================================================
INSERT INTO rooms (building, room_number, capacity, room_type, has_projector, has_video) VALUES
-- Hartley Hall — lecture rooms
('Hartley Hall', '101', 120, 'lecture',      TRUE,  TRUE),
('Hartley Hall', '102', 120, 'lecture',      TRUE,  TRUE),
('Hartley Hall', '201', 80,  'lecture',      TRUE,  FALSE),
('Hartley Hall', '202', 80,  'lecture',      TRUE,  FALSE),
('Hartley Hall', '203', 60,  'seminar',      TRUE,  FALSE),
('Hartley Hall', '204', 60,  'seminar',      TRUE,  FALSE),
('Hartley Hall', '301', 40,  'seminar',      TRUE,  FALSE),
('Hartley Hall', '302', 40,  'seminar',      TRUE,  FALSE),
('Hartley Hall', '303', 30,  'seminar',      FALSE, FALSE),
('Hartley Hall', '304', 30,  'seminar',      FALSE, FALSE),
-- Maxwell Science Building — labs and lectures
('Maxwell Science', '101', 200, 'lecture',   TRUE,  TRUE),
('Maxwell Science', '102', 150, 'lecture',   TRUE,  TRUE),
('Maxwell Science', 'L101', 24, 'lab',       TRUE,  FALSE),
('Maxwell Science', 'L102', 24, 'lab',       TRUE,  FALSE),
('Maxwell Science', 'L103', 24, 'lab',       TRUE,  FALSE),
('Maxwell Science', 'L201', 20, 'lab',       TRUE,  FALSE),
('Maxwell Science', 'L202', 20, 'lab',       TRUE,  FALSE),
('Maxwell Science', '201', 60,  'seminar',   TRUE,  FALSE),
('Maxwell Science', '202', 60,  'seminar',   TRUE,  FALSE),
('Maxwell Science', '301', 40,  'seminar',   TRUE,  FALSE),
-- Briggs Computing Center — computer labs
('Briggs Computing', 'A100', 40, 'computer_lab', TRUE, TRUE),
('Briggs Computing', 'A101', 40, 'computer_lab', TRUE, TRUE),
('Briggs Computing', 'A102', 40, 'computer_lab', TRUE, FALSE),
('Briggs Computing', 'A103', 30, 'computer_lab', TRUE, FALSE),
('Briggs Computing', 'B100', 30, 'computer_lab', TRUE, FALSE),
('Briggs Computing', 'B101', 25, 'computer_lab', TRUE, FALSE),
('Briggs Computing', 'B200', 20, 'computer_lab', TRUE, FALSE),
-- Ellsworth Hall — humanities seminar rooms
('Ellsworth Hall', '101', 100, 'lecture',    TRUE,  FALSE),
('Ellsworth Hall', '102', 80,  'lecture',    TRUE,  FALSE),
('Ellsworth Hall', '201', 35,  'seminar',    TRUE,  FALSE),
('Ellsworth Hall', '202', 35,  'seminar',    TRUE,  FALSE),
('Ellsworth Hall', '203', 35,  'seminar',    FALSE, FALSE),
('Ellsworth Hall', '301', 25,  'seminar',    FALSE, FALSE),
('Ellsworth Hall', '302', 25,  'seminar',    FALSE, FALSE),
-- Westbrook Business School
('Westbrook Business', '101', 150, 'lecture', TRUE, TRUE),
('Westbrook Business', '102', 100, 'lecture', TRUE, TRUE),
('Westbrook Business', '201', 60,  'seminar', TRUE, FALSE),
('Westbrook Business', '202', 60,  'seminar', TRUE, FALSE),
('Westbrook Business', '301', 40,  'seminar', TRUE, FALSE),
('Westbrook Business', '302', 40,  'seminar', TRUE, FALSE),
('Westbrook Business', 'L101', 30, 'computer_lab', TRUE, FALSE),
-- Prentiss Medical Sciences
('Prentiss Medical', '101', 180, 'lecture',  TRUE,  TRUE),
('Prentiss Medical', 'L101', 16, 'lab',      TRUE,  FALSE),
('Prentiss Medical', 'L102', 16, 'lab',      TRUE,  FALSE),
('Prentiss Medical', 'L103', 16, 'lab',      TRUE,  FALSE),
('Prentiss Medical', 'L201', 12, 'lab',      TRUE,  FALSE),
('Prentiss Medical', '201', 60,  'seminar',  TRUE,  FALSE),
-- Virtual placeholder room for fully online sections
('Online', 'VIRTUAL', 500, 'online', FALSE, FALSE);


-- ============================================================
--  scholarships  (20 rows)
-- ============================================================
INSERT INTO scholarships (name, amount, frequency, eligibility, is_active) VALUES
('Presidential Merit Scholarship',       8000.00, 'annual',       JSON_OBJECT('min_gpa', 3.8, 'need_based', FALSE), TRUE),
('Need-Based Excellence Grant',          5000.00, 'annual',       JSON_OBJECT('min_gpa', 2.5, 'need_based', TRUE,  'max_family_income', 60000), TRUE),
('STEM Achievement Award',               4000.00, 'annual',       JSON_OBJECT('min_gpa', 3.5, 'need_based', FALSE, 'majors', JSON_ARRAY('CS','Math','Physics','Biology','Chemistry')), TRUE),
('First-Generation College Award',       3500.00, 'annual',       JSON_OBJECT('min_gpa', 2.8, 'need_based', TRUE,  'first_gen', TRUE), TRUE),
('Dean''s List Scholarship',             3000.00, 'per-semester', JSON_OBJECT('min_gpa', 3.7, 'need_based', FALSE), TRUE),
('Women in Computing Fellowship',        4500.00, 'annual',       JSON_OBJECT('min_gpa', 3.3, 'need_based', FALSE, 'gender', 'F', 'majors', JSON_ARRAY('CS','Data Science','IT')), TRUE),
('International Student Bursary',        2500.00, 'per-semester', JSON_OBJECT('min_gpa', 3.0, 'need_based', TRUE,  'international', TRUE), TRUE),
('Community Leadership Award',           2000.00, 'one-time',     JSON_OBJECT('min_gpa', 2.5, 'need_based', FALSE), TRUE),
('Graduate Research Fellowship',         7000.00, 'annual',       JSON_OBJECT('min_gpa', 3.5, 'need_based', FALSE, 'level', 'graduate'), TRUE),
('Athletic Achievement Grant',           1500.00, 'per-semester', JSON_OBJECT('min_gpa', 2.0, 'need_based', FALSE, 'varsity_athlete', TRUE), TRUE),
('Library & Information Science Award',  2800.00, 'annual',       JSON_OBJECT('min_gpa', 3.2, 'need_based', FALSE, 'majors', JSON_ARRAY('Library Science','Information Science')), TRUE),
('Diversity & Inclusion Scholarship',    3200.00, 'annual',       JSON_OBJECT('min_gpa', 2.7, 'need_based', TRUE), TRUE),
('Biomedical Research Grant',            6000.00, 'annual',       JSON_OBJECT('min_gpa', 3.6, 'need_based', FALSE, 'majors', JSON_ARRAY('Biology','Chemistry','Medicine')), TRUE),
('Entrepreneurship Seed Award',          5000.00, 'one-time',     JSON_OBJECT('min_gpa', 3.0, 'need_based', FALSE), TRUE),
('Transfer Student Transition Grant',    1800.00, 'one-time',     JSON_OBJECT('min_gpa', 2.5, 'need_based', TRUE,  'transfer', TRUE), TRUE),
('Junior Year Abroad Scholarship',       2200.00, 'one-time',     JSON_OBJECT('min_gpa', 3.1, 'need_based', FALSE, 'min_year', 3), TRUE),
('Veteran Education Support Award',      4000.00, 'annual',       JSON_OBJECT('min_gpa', 2.0, 'need_based', TRUE,  'veteran', TRUE), TRUE),
('Arts & Humanities Excellence Prize',   2600.00, 'annual',       JSON_OBJECT('min_gpa', 3.4, 'need_based', FALSE, 'majors', JSON_ARRAY('Literature','History','Philosophy','Art')), TRUE),
('Data Science Innovation Award',        5500.00, 'annual',       JSON_OBJECT('min_gpa', 3.5, 'need_based', FALSE, 'majors', JSON_ARRAY('CS','Data Science','Statistics')), TRUE),
('Sustainability & Environment Grant',   2000.00, 'annual',       JSON_OBJECT('min_gpa', 2.9, 'need_based', FALSE), TRUE);


-- ============================================================
--  departments  (25 rows — 3-level hierarchy)
--  Level 1: University Faculties (5)
--  Level 2: Departments (15)
--  Level 3: Sub-departments / Research divisions (5)
--  head_faculty_id populated by generate_data.py after faculty are inserted
-- ============================================================
INSERT INTO departments (department_id, parent_id, code, name, level, head_faculty_id, established) VALUES
-- Level 1 — Faculties (no parent)
(1,  NULL, 'FAC-SCI',  'Faculty of Science & Engineering',  1, NULL, 1952),
(2,  NULL, 'FAC-ART',  'Faculty of Arts & Humanities',      1, NULL, 1948),
(3,  NULL, 'FAC-BUS',  'Faculty of Business',               1, NULL, 1961),
(4,  NULL, 'FAC-MED',  'Faculty of Medicine & Health',      1, NULL, 1970),
(5,  NULL, 'FAC-SOC',  'Faculty of Social Sciences',        1, NULL, 1955),

-- Level 2 — Departments (parent = a Level 1 Faculty)
(6,  1,    'CS',       'Computer Science',                  2, NULL, 1975),
(7,  1,    'MATH',     'Mathematics',                       2, NULL, 1952),
(8,  1,    'PHYS',     'Physics',                           2, NULL, 1952),
(9,  1,    'CHEM',     'Chemistry',                         2, NULL, 1952),
(10, 1,    'BIO',      'Biology',                           2, NULL, 1952),
(11, 2,    'ENGL',     'English & Literature',              2, NULL, 1948),
(12, 2,    'HIST',     'History',                           2, NULL, 1948),
(13, 2,    'PHIL',     'Philosophy',                        2, NULL, 1962),
(14, 3,    'ECON',     'Economics',                         2, NULL, 1961),
(15, 3,    'FINC',     'Finance',                           2, NULL, 1968),
(16, 3,    'MKTG',     'Marketing',                         2, NULL, 1975),
(17, 4,    'MED',      'Medicine',                          2, NULL, 1970),
(18, 4,    'NURS',     'Nursing',                           2, NULL, 1972),
(19, 5,    'PSY',      'Psychology',                        2, NULL, 1960),
(20, 5,    'SOC',      'Sociology',                         2, NULL, 1955),

-- Level 3 — Sub-departments / Research divisions (parent = a Level 2 Dept)
(21, 6,    'CS-AI',    'Artificial Intelligence & ML',      3, NULL, 1998),
(22, 6,    'CS-SEC',   'Cybersecurity & Networks',          3, NULL, 2003),
(23, 6,    'CS-DB',    'Database & Information Systems',    3, NULL, 1990),
(24, 7,    'MATH-STAT','Statistics & Data Science',         3, NULL, 2005),
(25, 10,   'BIO-GEN',  'Genetics & Genomics',               3, NULL, 2010);
